{{- if .Values.database.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "homenavi-marketplace.fullname" . }}-db
  labels:
    {{- include "homenavi-marketplace.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.persistence.size }}
  {{- if .Values.database.persistence.storageClassName }}
  storageClassName: {{ .Values.database.persistence.storageClassName }}
  {{- end }}
{{- end }}
