apiVersion: v1
kind: Secret
metadata:
  name: {{ include "homenavi-marketplace.fullname" . }}-db
  labels:
    {{- include "homenavi-marketplace.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.database.auth.database | quote }}
  POSTGRES_USER: {{ .Values.database.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.auth.password | quote }}
  DATABASE_URL: {{ printf "postgres://%s:%s@%s-db:%d/%s?sslmode=disable" .Values.database.auth.username .Values.database.auth.password (include "homenavi-marketplace.fullname" .) (int .Values.database.service.port) .Values.database.auth.database | quote }}
